name: CI

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint with Ruff
        run: ruff check src tests --quiet
      - name: Run Pytest (with placeholder)
        run: pytest -n auto # -n auto para pytest-xdist
      - name: Run Behave (with placeholder)
        run: behave -f progress # Para mas adelante